FROM openjdk:17-jdk

WORKDIR /app

COPY target/*.jar app.jar

EXPOSE 8080

ENV DATABASE_URL=${DATABASE_URL}
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENV AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
ENV AWS_ACCESS_SECRET_KEY=${AWS_ACCESS_SECRET_KEY}
ENV AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
ENV AWS_REGION=${AWS_REGION}
ENV SMTP_MAIL_USERNAME=${SMTP_MAIL_USERNAME}
ENV SMTP_MAIL_PASSWORD=${SMTP_MAIL_PASSWORD}
ENV BASE_URL=${BASE_URL}

ENTRYPOINT ["java", "-jar", "app.jar"]