services:
  security-db:
    container_name: security-db
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: security-db




