name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build and push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: 'Set up jdk 17'
        uses:  actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: 'Build with maven'
        run: mvn clean install -DskipTests

      - name: 'Generate tag'
        id: generate_tag
        run: |
            SHA=$(echo $GITHUB_SHA | head -c7)
            echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: 'Login into the container registry'
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: 'Build and Push'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: thiago0503/security-app:${{steps.generate_tag.outputs.sha}}, thiago0503/security-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image docker hub
        run:  docker pull thiago0503/security-app:latest
      - name: remove container
        run: docker rm -f security-app
      - name: Run docker container
        run: docker run -d -p 8080:8080 -e DATABASE_URL='${{secrets.DATABASE_URL}}' -e AWS_ACCESS_KEY='${{secrets.AWS_ACCESS_KEY}}' -e AWS_ACCESS_SECRET_KEY='${{secrets.AWS_ACCESS_SECRET_KEY}}' -e AWS_REGION='${{secrets.AWS_REGION}}' -e AWS_S3_BUCKET_NAME='${{secrets.AWS_S3_BUCKET_NAME}}' -e BASE_URL='${{secrets.BASE_URL}}' -e GOOGLE_CLIENT_ID='${{secrets.GOOGLE_CLIENT_ID}}' -e GOOGLE_CLIENT_SECRET='${{secrets.GOOGLE_CLIENT_SECRET}}' -e SMTP_MAIL_PASSWORD='${{secrets.SMTP_MAIL_PASSWORD}}' -e SMTP_MAIL_USERNAME='${{secrets.SMTP_MAIL_USERNAME}}' -e TOKEN_SECRET='${{secrets.TOKEN_SECRET}}' --name security-app thiago0503/security-app:latest